import type { Lang } from '../i18n.tsx'

const it = {
  title: 'Pannello di amministrazione',
  preview: 'Anteprima dimostrativa: le modifiche si salvano solo in questo browser e il sito le mostra solo qui.',
  viewSite: 'Apri il sito',
  tabPhotos: 'Foto',
  tabCategories: 'Categorie',
  tabSite: 'Foto del sito',
  tabTexts: 'Testi',
  tabs: 'Sezioni del pannello',
  save: 'Salva modifiche',
  saving: 'Salvataggio…',
  saved: 'Tutto salvato',
  unsaved: 'Modifiche non salvate',
  saveError: 'Salvataggio non riuscito. Le modifiche sono ancora qui: riprova.',
  reset: 'Ripristina contenuti originali',
  resetConfirm: 'Ripristinare foto, categorie e testi originali? Le modifiche salvate andranno perse.',
  loading: 'Caricamento…',
  loadError: 'Impossibile caricare i contenuti. Ricarica la pagina.',
  loginTitle: 'Accedi',
  password: 'Password',
  loginBtn: 'Entra',
  loginError: 'Password errata.',
  loginFail: 'Accesso non riuscito. Riprova.',
  logout: 'Esci',
  expired: 'Sessione scaduta: accedi di nuovo, poi salva. Le modifiche non sono andate perse.',
  upload: 'Carica foto',
  uploading: 'Elaborazione {n} di {m}…',
  uploadError: 'Impossibile caricare {f}.',
  webp: 'Questo browser non sa creare immagini WebP. Usa Chrome, Edge o Firefox aggiornati.',
  filterAll: 'Tutte',
  count: '{n} foto',
  collection: 'Categoria',
  altIt: 'Descrizione (IT)',
  altEn: 'Descrizione (EN)',
  featured: 'In evidenza',
  replace: 'Sostituisci immagine',
  delete: 'Elimina',
  deletePhoto: 'Eliminare questa foto?',
  moveUp: 'Sposta prima',
  moveDown: 'Sposta dopo',
  catIt: 'Nome (IT)',
  catEn: 'Nome (EN)',
  catAdd: 'Aggiungi categoria',
  catNew: 'Nuova categoria',
  catBlocked: 'Contiene {n} foto: spostale o eliminale prima.',
  catDelete: 'Eliminare la categoria {c}?',
  catExists: 'Esiste già una categoria con questo nome.',
  siteLead: 'Scegli le foto della prima schermata e della sezione Chi siamo. Le copertine delle categorie usano le foto in evidenza.',
  heroMain: 'Prima schermata: foto ad arco',
  heroTop: 'Prima schermata: foto in alto',
  heroBottom: 'Prima schermata: foto in basso',
  aboutPhoto: 'Chi siamo: ritratto',
  pick: 'Usa questa foto: {a}',
  enterHint: 'Premi Invio per tradurre automaticamente nell’altra lingua, se è vuota.',
  translating: 'Traduzione…',
  translated: 'Tradotto in {l}',
  translateError: 'Traduzione non riuscita. Riprova o scrivi il testo a mano.',
  translateNote: 'La traduzione automatica usa il servizio MyMemory: controlla sempre il risultato.',
  textsLead: 'Ecco le sezioni del sito come appaiono ai visitatori. Clicca su un testo e scrivi per cambiarlo. Stai modificando la versione {l}: cambia lingua con il selettore in alto a destra.',
  textsEnter: 'Premi Invio dopo aver modificato un testo: se la versione {o} di quel testo non è mai stata modificata, viene tradotta automaticamente.',
  inOther: 'In {l}:',
  edited: 'modificato',
  occHint: 'Le occasioni sono separate da |',
  countHint: 'Etichette sotto ogni collezione: {n} è il numero di foto.',
  many: 'più foto',
  one: 'una foto',
  'lang.it': 'italiana',
  'lang.en': 'inglese',
  's.menu': 'Menu in alto',
  's.hero': 'Prima schermata',
  's.about': 'Chi siamo',
  's.col': 'Collezioni',
  's.gal': 'Galleria',
  's.contact': 'Contatti',
  's.footer': 'Fondo pagina',
}

export type AdminKey = keyof typeof it

const en: Record<AdminKey, string> = {
  title: 'Admin panel',
  preview: 'Demo preview: changes are saved only in this browser, and the site shows them only here.',
  viewSite: 'Open the site',
  tabPhotos: 'Photos',
  tabCategories: 'Categories',
  tabSite: 'Site photos',
  tabTexts: 'Texts',
  tabs: 'Panel sections',
  save: 'Save changes',
  saving: 'Saving…',
  saved: 'All saved',
  unsaved: 'Unsaved changes',
  saveError: 'Saving failed. Your changes are still here: try again.',
  reset: 'Restore original content',
  resetConfirm: 'Restore the original photos, categories and texts? Saved changes will be lost.',
  loading: 'Loading…',
  loadError: 'Could not load the content. Reload the page.',
  loginTitle: 'Sign in',
  password: 'Password',
  loginBtn: 'Sign in',
  loginError: 'Wrong password.',
  loginFail: 'Sign-in failed. Try again.',
  logout: 'Sign out',
  expired: 'Session expired: sign in again, then save. Your changes were not lost.',
  upload: 'Upload photos',
  uploading: 'Processing {n} of {m}…',
  uploadError: 'Could not upload {f}.',
  webp: 'This browser cannot create WebP images. Use an up-to-date Chrome, Edge or Firefox.',
  filterAll: 'All',
  count: '{n} photos',
  collection: 'Category',
  altIt: 'Description (IT)',
  altEn: 'Description (EN)',
  featured: 'Featured',
  replace: 'Replace image',
  delete: 'Delete',
  deletePhoto: 'Delete this photo?',
  moveUp: 'Move earlier',
  moveDown: 'Move later',
  catIt: 'Name (IT)',
  catEn: 'Name (EN)',
  catAdd: 'Add category',
  catNew: 'New category',
  catBlocked: 'Contains {n} photos: move or delete them first.',
  catDelete: 'Delete the category {c}?',
  catExists: 'A category with this name already exists.',
  siteLead: 'Choose the photos for the first screen and the About section. Category covers use featured photos.',
  heroMain: 'First screen: arch photo',
  heroTop: 'First screen: top photo',
  heroBottom: 'First screen: bottom photo',
  aboutPhoto: 'About: portrait',
  pick: 'Use this photo: {a}',
  enterHint: 'Press Enter to translate automatically into the other language, if it is empty.',
  translating: 'Translating…',
  translated: 'Translated into {l}',
  translateError: 'Translation failed. Try again or type the text yourself.',
  translateNote: 'Automatic translation uses the MyMemory service: always check the result.',
  textsLead: 'These are the site sections as visitors see them. Click a text and type to change it. You are editing the {l} version: switch language with the toggle at the top right.',
  textsEnter: 'Press Enter after changing a text: if the {o} version of that text was never changed, it is translated automatically.',
  inOther: 'In {l}:',
  edited: 'edited',
  occHint: 'Occasions are separated by |',
  countHint: 'Labels under each collection: {n} is the number of photos.',
  many: 'several photos',
  one: 'one photo',
  'lang.it': 'Italian',
  'lang.en': 'English',
  's.menu': 'Top menu',
  's.hero': 'First screen',
  's.about': 'About',
  's.col': 'Collections',
  's.gal': 'Gallery',
  's.contact': 'Contact',
  's.footer': 'Footer',
}

const dict: Record<Lang, Record<AdminKey, string>> = { it, en }

export type T = (k: AdminKey, vars?: Record<string, string | number>) => string

// Placeholders are filled only when vars are passed, so hints can show literal {n}.
export const makeT =
  (lang: Lang): T =>
  (k, vars) => {
    let s = dict[lang][k]
    if (vars) for (const [n, v] of Object.entries(vars)) s = s.replace(`{${n}}`, String(v))
    return s
  }
